### ISSUE TITLE
Installation issue with python 3.12

### ISSUE THREAD

**Issue by adelaneh** [dynamicslab/pykoopman#41]
Fresh env. Tried both pypi and source installation: Got the following error:

```
Collecting scikit-learn<=1.1.3,>=1.1.3 (from pykoopman==1.0.8)
  Using cached scikit-learn-1.1.3.tar.gz (7.0 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [33 lines of output]
      Traceback (most recent call last):
        File "anaconda3/envs/koopman/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "anaconda3/envs/koopman/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "anaconda3/envs/koopman/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 112, in get_requires_for_build_wheel
          backend = _build_backend()
                    ^^^^^^^^^^^^^^^^
        File "anaconda3/envs/koopman/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 77, in _build_backend
          obj = import_module(mod_path)
                ^^^^^^^^^^^^^^^^^^^^^^^
        File "anaconda3/envs/koopman/lib/python3.12/importlib/__init__.py", line 90, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<frozen importlib._bootstrap>", line 1381, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1354, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1304, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "<frozen importlib._bootstrap>", line 1381, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1354, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1325, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 929, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 994, in exec_module
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "/private/var/folders/1h/vpctqsm57x32h6_lcv8v2c0c0000gn/T/pip-build-env-rmmozt_b/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 16, in <module>
          import setuptools.version
        File "/private/var/folders/1h/vpctqsm57x32h6_lcv8v2c0c0000gn/T/pip-build-env-rmmozt_b/overlay/lib/python3.12/site-packages/setuptools/version.py", line 1, in <module>
          import pkg_resources
        File "/private/var/folders/1h/vpctqsm57x32h6_lcv8v2c0c0000gn/T/pip-build-env-rmmozt_b/overlay/lib/python3.12/site-packages/pkg_resources/__init__.py", line 2172, in <module>
          register_finder(pkgutil.ImpImporter, find_on_path)
                          ^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

Issue resolved when reverted to python 3.10

**Comment by pswpswpsw** [comment]
Interesting. I didn't see that one coming. Indeed, I am using 3.10 for development. I will add that requirement in the installation section. Thanks

**Comment by raubenheimer** [comment]
This issue seems to be caused by the Matlab dependency matplotlib == 3.5.0. Something about PEP517. If you upgrade the dependency to 3.6.0 it works fine on 3.12.

**Comment by J-Massey** [comment]
> This issue seems to be caused by the Matlab dependency matplotlib == 3.5.0. Something about PEP517. If you upgrade the dependency to 3.6.0 it works fine on 3.12.

I'm also having this issue, this seems like an easy fix. I'll check for my install later today.

**Comment by GeoffChurch** [comment]
> This issue seems to be caused by the Matlab dependency matplotlib == 3.5.0. Something about PEP517. If you upgrade the dependency to 3.6.0 it works fine on 3.12.

It still failed for me, but making every dependency a lower bound ended up working:
```toml
dependencies = [
    "matplotlib >=3.6.0",
    "derivative ~= 0.6.0",
    "scikit-learn >= 1.1.3",
    "numpy >=1.20",
    "scipy >1.6.0",
    "pydmd >0.4",
    "optht ~= 0.2.0",
    "prettytable >3.0.0",
    "torch >= 2.1.0",
    "torchvision >= 0.16.0",
    "torchaudio >= 2.1.0",
    "lightning >= 2.0.9",
]
```

**Comment by pswpswpsw** [comment]
Thanks. I fixed the issue with ```matplotlib >= 3.6.0```
